"""What a run actually established, kept so it can be explained afterwards.

Deterministic code computes a great deal during a run — how many compatible units
existed, which supplier tier won and what lost to it, whether the case filled exactly,
which pickup site covered the most people, and, per declaration, the specific condition
that left somebody out. Almost all of it was discarded the moment the run ended. What
survived was a count and a one-line tool summary, so the only way to explain a result
afterwards was to *recompute* it — which answers a different question. Current state and
"what this run found" diverge the instant anything else changes, and presenting the
first as the second is the kind of retrospective omniscience AGENTS.md §8 forbids.

So the run writes down what it evaluated, once, at the end of its own execution.

Three constraints shape this module, and each one removed an easier design:

**It must survive the process.** The complete tool results live on
:class:`~pool.agent.tools.ToolContext`, and after an AgentCore run that object is in a
microVM that no longer exists. The API cannot read it. So the records are written
through the repository, from inside the run, and the deployed runtime and the local API
produce identical rows.

**It must contain no model reasoning.** Everything below is a deterministic service's
own value — a verdict, a reason code, a quantity, an identifier. Nothing the model wrote,
no scratchpad, no narration, and nothing generated by asking a model to explain itself
(AGENTS.md §9).

**It must not become a readout of other people's private state.** An evaluation touches
every declaration in the Community. ``need_verdicts`` carries only the declarations *this
run was asked about* — the member's own — so a report can say "your units did not fit
this case" without also publishing why six neighbours were excluded. No names, no contact
details, no payment references, and every list is capped.
"""

from __future__ import annotations

from typing import Any

from ..domain.models import (
    MAX_EVALUATION_NEED_VERDICTS,
    MAX_EVALUATION_TIERS,
    RunEvaluation,
    new_id,
)

#: Evaluations persisted per run. The tool-call bound already caps how many a run can
#: perform; this is the backstop that stops a mis-set bound growing storage without
#: limit (AGENTS.md §3.1).
MAX_EVALUATIONS_PER_RUN = 12


def _need_verdicts(
    assessment: dict[str, Any], need_ids: set[str]
) -> list[dict[str, Any]]:
    """Per-declaration outcome, for the declarations this run was asked about only."""
    if not need_ids:
        return []
    selected = {
        c["need_id"]: c for c in assessment.get("candidates") or [] if c.get("need_id")
    }
    rejected = {
        r["need_id"]: str(r.get("reason", ""))
        for r in assessment.get("rejected") or []
        if r.get("need_id")
    }
    out: list[dict[str, Any]] = []
    for need_id in sorted(need_ids):
        if need_id in selected:
            out.append(
                {
                    "need_id": need_id,
                    "included": True,
                    "units": int(selected[need_id].get("units", 0) or 0),
                    "reason": "",
                }
            )
        elif need_id in rejected:
            raw = rejected[need_id]
            out.append(
                {
                    "need_id": need_id,
                    "included": False,
                    "units": 0,
                    # The matcher's own structured reason, with its namespace prefix
                    # removed. Never reworded here: the sentence a member reads is the
                    # presentation layer's job, and it needs the value to key off.
                    "reason": raw.split(":", 1)[1].strip() if ":" in raw else raw,
                }
            )
        else:
            # Compatible, in range, in time — and not selected. That is the case
            # boundary, which is a different thing from being rejected and has to read
            # as one (§48).
            out.append({"need_id": need_id, "included": False, "units": 0, "reason": ""})
    return out[:MAX_EVALUATION_NEED_VERDICTS]


def build(
    *,
    run_id: str,
    community_id: str,
    full_results: list[Any],
    objective: Any,
    pool_ids_by_product: dict[str, str],
    sites_considered: int,
) -> list[RunEvaluation]:
    """Turn one run's authoritative tool results into durable evaluation records.

    Reads the *unprojected* results the deterministic services produced, not the compact
    views the model was shown — the model's copy is a cost optimisation, and explaining a
    decision from it would explain the optimisation.
    """
    needs_by_product: dict[str, set[str]] = {}
    for entry in getattr(objective, "needs", ()) or ():
        for product_id in entry.target_product_ids:
            needs_by_product.setdefault(product_id, set()).add(entry.need_id)

    out: list[RunEvaluation] = []
    seen: set[tuple[str, str]] = set()
    for result in full_results:
        if result.tool != "evaluate_pool_economics":
            continue
        a = result.result
        product_id = str(a.get("product_id", ""))
        site_id = str(a.get("pickup_site_id", ""))
        if not product_id or (product_id, site_id) in seen:
            continue
        seen.add((product_id, site_id))
        if len(out) >= MAX_EVALUATIONS_PER_RUN:
            break

        econ = a.get("economics") or {}
        packages = econ.get("packages") or {}
        candidates = a.get("candidates") or []
        out.append(
            RunEvaluation(
                id=new_id("eval"),
                run_id=run_id,
                community_id=community_id,
                product_id=product_id,
                product_name=str(a.get("product_name", "")),
                need_ids=sorted(needs_by_product.get(product_id, set())),
                viable=bool(a.get("viable")),
                reason_code=str(a.get("reason_code", "")),
                reason=str(a.get("reason", ""))[:300],
                pickup_site_id=site_id,
                pickup_site_name=str(a.get("pickup_site_name", "")),
                sites_considered=sites_considered,
                distribution_day=str(a.get("distribution_day", "")),
                matched_units=int(a.get("matched_units", 0) or 0),
                minimum_units=int(a.get("minimum_units", 0) or 0),
                current_units=int(a.get("current_units", 0) or 0),
                future_units=int(a.get("future_units", 0) or 0),
                selected_units=int(packages.get("total_units", 0) or 0),
                selected_member_count=len(candidates),
                cases=int(packages.get("cases", 0) or 0),
                case_units=int(packages.get("case_units", 0) or 0),
                surplus_units=int(packages.get("surplus_units", 0) or 0),
                auto_join_count=int(a.get("auto_join_count", 0) or 0),
                approval_required_count=int(a.get("approval_required_count", 0) or 0),
                bulk_offer_id=str(a.get("bulk_offer_id") or ""),
                retail_offer_id=str(a.get("retail_offer_id") or ""),
                offers_considered=list(a.get("offers_considered") or [])[
                    :MAX_EVALUATION_TIERS
                ],
                all_in_cents=int(econ.get("all_in_cents", 0) or 0),
                retail_baseline_cents=int(econ.get("retail_baseline_cents", 0) or 0),
                net_savings_cents=int(econ.get("net_savings_cents", 0) or 0),
                net_savings_bps=int(econ.get("net_savings_bps", 0) or 0),
                host_compensation_cents=int(econ.get("host_compensation_cents", 0) or 0),
                platform_fee_cents=int(econ.get("platform_fee_cents", 0) or 0),
                processing_fee_cents=int(econ.get("processing_fee_cents", 0) or 0),
                need_verdicts=_need_verdicts(a, needs_by_product.get(product_id, set())),
                pool_id=pool_ids_by_product.get(product_id, ""),
            )
        )
    return out
